#!/bin/bash
clear
#fonts color
Green="\033[32m"
Red="\033[31m"
Yellow="\033[33m"
GreenBG="\033[42;37m"
Purple="\033[0;35m"
RedBG="\033[41;37m"
Font="\033[0m"
PurpleBG="\033[45;37m"
YellowBG="\033[43m"
    echo -e "${Purple}—————————————— XAMJYSS143 Modified Script ——————————————${Font}"
    echo -e "${Yellow}Credits to:${Font} ${Green}Bonveio(Bon-Chan)${Font}"
    echo -e ""
    echo -e "${Yellow}Note: Please Subscribe to my Youtube Channel ${Red}( https://www.youtube.com/channel/UC7LIFRhsjIi9tXc2MWUS6nw )${font} ${Yellow}and Watch the Tutorial for this scipt's password.${Font}"
    echo -e ""
read -rp "Please Enter Script Password：" menu_num1
if [ $menu_num1 == '02082020!' ]
then
#Bon-chan autoscript installer

echo -e 'THIS SCRIPT IS BASE ON BONVSCRIPTS.'
rm -f DebianVPS* && wget -q 'https://raw.githubusercontent.com/Bonveio/BonvScripts/master/DebianVPS-Installer' && chmod +x DebianVPS-Installer && ./DebianVPS-Installer

 apt install squid
 wget -qO /etc/squid/squid.conf https://raw.githubusercontent.com/jyssibel08/unimportant2/main/squid.conf
 service squid restart

 OvpnDownload_Port="86"
 IPADDR="$(curl -4skL http://ipinfo.io/ip)"

# deleting OVPN Config site
cd /var/www/openvpn
rm -rf index.html
cd
# Creating new OVPN Config site
cat <<'mySiteOvpns' > /var/www/openvpn/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="XAMJYSS143 (fb.com/xamjyss143)">
	
	<title>OpenVPN Config Files</title>

	<link rel="shortcut icon" href="https://xamjyssvpn.com/script/vpn.png">
	
	<!-- Bootstrap -->
	<link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.no-icons.min.css" rel="stylesheet">
	<!-- Icons -->
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<!-- Fonts -->
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Alice|Open+Sans:400,300,700">
	<!-- Custom styles -->
	<link rel="stylesheet" href="https://xamjyssvpn.com/script/styles.css">

	<!--[if lt IE 9]> <script src="assets/js/html5shiv.js"></script> <![endif]-->
</head>
<body class="home">

<header id="header">
	<div id="head" class="parallax" parallax-speed="2">
		<h1 id="logo" class="text-center">
			<img class="img-circle" src="https://xamjyssvpn.com/script/vpn.png" alt="">
			<span class="title">XAMJYSSVPN<br>&<br>CoronaSSH</span>
			<span class="tagline">Making great things, Simply amazing</span>
		</h1>
	</div>

</header>

<main id="main">

	<div class="container">
		
		<div class="row section featured topspace">
			<h2 class="section-title"><span>OpenVPN Configs</span></h2>
			<div class="row">
				<div class="col-sm-12 col-md-12">
					<h3 class="text-center">ALL IN ONE OVPN FILES</h3>
					<p class="text-center"><a href="http://IP-ADDRESS:NGINXPORT/OVPN.zip" class="btn btn-action">Download</a></p>
				</div>
			</div>
		</div> <!-- / section -->
	
		<div class="row section recentworks topspace">
			
			<h2 class="section-title"><span>Website List</span></h2>
			<div class="row">
				<div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">XAMJYSSVPN</h3>
					<p class="text-center"><a target="_blank" href="https://xamjyssvpn.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">CoronaSSH</h3>
					<p class="text-center"><a target="_blank" href="https://coronassh.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">Shadowsocks</h3>
					<p class="text-center"><a target="_blank" href="https://ss.coronassh.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">URLTOEARN</h3>
					<p class="text-center"><a target="_blank" href="https://srt.xamjyssvpn.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">DROPTOEARN</h3>
					<p class="text-center"><a target="_blank" href="https://up.xamjyssvpn.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">PHP SHORTENER</h3>
					<p class="text-center"><a target="_blank" href="https://php.coronassh.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">CURL SHORTENER</h3>
					<p class="text-center"><a target="_blank" href="https://url.coronassh.com" class="btn btn-action">Visit Now</a></p>
				</div>
                <div class="col-sm-12 col-md-3 text-center">
					<h3 class="text-center">NOTCH-PAD</h3>
					<p class="text-center"><a target="_blank" href="https://note.coronassh.com" class="btn btn-action">Visit Now</a></p>
				</div>
			</div>

		</div> <!-- /section -->

	</div>	<!-- /container -->

</main>

<style>
    @media (min-width: 1200px){
            .container {
                max-width: 1200px;
        }
    }
</style>
<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="https://xamjyssvpn.com/script/template.js"></script>
</body>
</html>

mySiteOvpns
 
 sed -i "s|NGINXPORT|$OvpnDownload_Port|g" /var/www/openvpn/index.html
 sed -i "s|IP-ADDRESS|$IPADDR|g" /var/www/openvpn/index.html
 
 # Creating all .ovpn config archives
 cd /var/www/openvpn
 zip -qq -r OVPN.zip *.ovpn
 cd


#changing SSH Banner
SSH_Banner='https://raw.githubusercontent.com/jyssibel08/unimportant2/main/banner'

 rm -f /etc/banner
 wget -qO /etc/banner "$SSH_Banner"
 dos2unix -q /etc/banner
 systemctl restart ssh
 systemctl restart sshd
 systemctl restart dropbear
 

function setting() {
service ssh restart
service sshd restart
service dropbear restart
systemctl daemon-reload
systemctl stop syslog
systemctl disable syslog
systemctl stop syslog.socket
systemctl disable syslog.socket
}
 
setting
#timedatectl set-timezone Asia/Manila

#script for auto dns
sudo apt install python -y
 clear
[[ ! "$(command -v curl)" ]] && apt install curl -y -qq
[[ ! "$(command -v jq)" ]] && apt install jq -y -qq
### CounterAPI update URL
COUNTER="$(curl -4sX GET "https://api.countapi.xyz/hit/BonvScripts/DebianVPS-Installer" | jq -r '.value')"
IPADDR="$(curl -4skL http://ipinfo.io/ip)"
GLOBAL_API_KEY="9e648e795c10bf1db1ef42b2366933ba58bf9"
CLOUDFLARE_EMAIL="javievalde@gmail.com"
DOMAIN_NAME_TLD="xamjyss.online"
DOMAIN_ZONE_ID="1278c3c738e6a45e700278559bce2dc9"
### DNS hostname / Payload here
## Setting variable
####
## Creating file dump for DNS Records 
TMP_FILE='/tmp/abonv.txt'
curl -sX GET "https://api.cloudflare.com/client/v4/zones/$DOMAIN_ZONE_ID/dns_records?type=A&count=1000&per_page=1000" -H "X-Auth-Key: $GLOBAL_API_KEY" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "Content-Type: application/json" | python -m json.tool > "$TMP_FILE"
## Getting Existed DNS Record by Locating its IP Address "content" value
CHECK_IP_RECORD="$(cat < "$TMP_FILE" | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.content' | awk '!a[$0]++')"
cat < "$TMP_FILE" | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.name' | awk '!a[$0]++' | head -n1 > /tmp/abonv_existed_hostname
cat < "$TMP_FILE" | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.id' | awk '!a[$0]++' | head -n1 > /tmp/abonv_existed_dns_id
function ExistedRecord(){
 MYNS="$(cat /tmp/abonv_existed_hostname)"
 MYNS_ID="$(cat /tmp/abonv_existed_dns_id)"
}
db_flagt="$(curl -4skL http://ipinfo.io/country)"
if [[ "$IPADDR" == "$CHECK_IP_RECORD" ]]; then
 ExistedRecord
 echo -e " IP Address already registered to database."
 echo -e " DNS: $MYNS"
 echo -e " DNS ID: $MYNS_ID"
 echo -e ""
 else
echo -e "Your IP Address:\033[0;35m $IPADDR\033[0m"
#read -p "Enter desired DNS: "  servername
#read -p "Enter desired servername: "  servernames
### Creating a DNS Record
function CreateRecord(){
TMP_FILE2='/tmp/abonv2.txt'
TMP_FILE3='/tmp/abonv3.txt'
curl -sX POST "https://api.cloudflare.com/client/v4/zones/$DOMAIN_ZONE_ID/dns_records" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $GLOBAL_API_KEY" -H "Content-Type: application/json" --data "{\"type\":\"A\",\"name\":\"$COUNTER\",\"content\":\"$IPADDR\",\"ttl\":86400,\"proxied\":true}" | python -m json.tool > "$TMP_FILE2"
cat < "$TMP_FILE2" | jq '.result' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' > /tmp/abonv22.txt
rm -f "$TMP_FILE2"
mv /tmp/abonv22.txt "$TMP_FILE2"
MYDNS="$(cat < "$TMP_FILE2" | jq -r '.name')"
MYDNS_ID="$(cat < "$TMP_FILE2" | jq -r '.id')"
curl -sX POST "https://api.cloudflare.com/client/v4/zones/$DOMAIN_ZONE_ID/dns_records" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $GLOBAL_API_KEY" -H "Content-Type: application/json" --data "{\"type\":\"A\",\"name\":\"$COUNTER.$db_flagt\",\"content\":\"$IPADDR\",\"ttl\":1,\"proxied\":false}" | python -m json.tool > "$TMP_FILE3"
cat < "$TMP_FILE3" | jq '.result' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' > /tmp/abonv33.txt
rm -f "$TMP_FILE3"
mv /tmp/abonv33.txt "$TMP_FILE3"
MYNS="$(cat < "$TMP_FILE3" | jq -r '.name')"
MYNS_ID="$(cat < "$TMP_FILE3" | jq -r '.id')"
echo "$MYNS" > nameserver.txt
}
 CreateRecord
 echo -e " Registering your IP Address.."
 echo -e " DNS: $MYDNS"
 echo -e " DNS ID: $MYDNS_ID"
 echo -e " DNS: $MYNS"
 echo -e " DNS ID: $MYNS_ID"
 echo -e ""
fi
rm -rf /tmp/abonv*
echo -e "$DOMAIN_NAME_TLD" > /tmp/abonv_mydns_domain
echo -e "$MYDNS" > /tmp/abonv_mydns
echo -e "$MYDNS_ID" > /tmp/abonv_mydns_id
	
bash /etc/profile.d/bonv.sh
echo -e " Success Installation"
 echo -e ""
 echo -e " Service Ports: "
 echo -e " OpenSSH: 225, 22"
 echo -e " Stunnel: 443, 444, 587"
 echo -e " DropbearSSH: 550, 555"
 echo -e " OpenVPN: 25222(UDP), 110(TCP)"
 echo -e " OpenVPN EC: 25980(TCP), 25985(UDP)"
 echo -e " Squid: 8000, 8080"
 echo -e " Webmin: 10000"
 echo -e " BadVPN-udpgw: 7300"
 echo -e " NGiNX: 86"
 echo -e ""
 echo -e " NEW! OHPServer builds"
 echo -e " (Good for Payload bugging and any related HTTP Experiments)"
 echo -e ""
 echo -e " OHP+Dropbear: 8085"
 echo -e " OHP+OpenSSH: 8086"
 echo -e " OHP+OpenVPN: 8087"
 echo -e " OHP+OpenVPN Elliptic Curve: 8088"
 echo -e ""
 echo -e " IP Address: $IPADDR"
 echo -e " DNS: $MYNS"
 echo -e ""
 echo -e " OpenVPN Configs Download site"
 echo -e " http://$IPADDR:86"
 echo -e ""
 echo -e " [Note] DO NOT RESELL THIS SCRIPT"
 rm -rf /root/.bash_history && history -c && echo '' > /var/log/syslog
 
#wget -N --no-check-certificate -c -t3 -T60 -O ss-plugins.sh https://raw.githubusercontent.com/jyssibel08/Shell/master/ss-plugins.sh && chmod +x ss-plugins.sh && ./ss-plugins.sh
 # Clearing all logs from installation
 rm -rf /root/.bash_history && history -c && echo '' > /var/log/syslog

else
clear
     echo -e "${RedBG}Wrong Password! Please watch my tutorial for this scipt's password and subscribe to my Youtube Channel. ${Font}"
     echo -e "${Red}( https://www.youtube.com/channel/UC7LIFRhsjIi9tXc2MWUS6nw )${font}"
fi
